name: CI
#https://docs.github.com/cn/actions/using-workflows/triggering-a-workflow
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'k8s/*'
      - 'devops/*'
      - 'traefik/*'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'k8s/*'
      - 'devops/*'

jobs:
  push-to-registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            yaoyaoio/blog-v2
          tags: |
            type=sha,enable=true,priority=100,prefix=sha-,suffix=,format=short
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
#  build-and-deploy-on-github:
#    name: Build and Deploy Blog on Github
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v2.3.1
#      - name: Install and Build
#        run: |
#          yarn install
#          yarn docs:build
#      - name: Deploy
#        uses: JamesIves/github-pages-deploy-action@4.1.4
#        with:
#          branch: gh-pages
#          folder: docs/.vuepress/dist
#          token: ${{ secrets.ACCESS_TOKEN }}
