apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-v2-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/yaoliu/blog-v2.git
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: home-work
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
